### ISSUE TITLE
YAML file patterns

### ISSUE THREAD

**Issue by JackColquitt** [trustgraph-ai/trustgraph#204]
The release YAML files don't account for all the permutations now with Memgraph, Pinecone, and Milvus. Is creating an individual YAML file for each permutation the right approach? Having a YAML file for each permutation quickly explodes into a huge number of YAML files, but at the same time, some integrations like Pinecone follow a different YAML pattern.

**Comment by cybermaggedon** [comment]
Having discussed this, the release bundle now includes just the Ollama & Cassandra integration as a way to get started.

The templates utils are documented here:
https://github.com/trustgraph-ai/trustgraph/blob/master/templates/README.md

And the config portal covers generating your own configuration file:
Dev: https://dev.config-ui.demo.trustgraph.ai
Stable: https://config-ui.demo.trustgraph.ai
