### ISSUE TITLE
pulsar timeout

### ISSUE THREAD

**Issue by jonabert** [trustgraph-ai/trustgraph#46]
did everything exactly as prescribed. Kept on getting pulsar timeout errors
(env) (base) jonathan@GAMER005:~/trustgraph/trustgraph$ scripts/loader -f sources/Challenger-Report-Vol1.pdf
Exception: Pulsar error: TimeOut
Will retry...
Exception: Pulsar error: TimeOut
Will retry...

**Comment by cybermaggedon** [comment]
Hey @jonabert do you find it works if you leave it for a bit longer?  Which docker compose are you using?

**Comment by JackColquitt** [comment]
Hi @jonabert are you using Linux or MacOS? Also, are you using Docker or Podman? I typically use Podman on MacOS. One of the things I've found is I have to increase the default memory allocations for a few containers. For instance, I config Pulsar this way, increasing both the memory limit and reservations:

```
  "pulsar":
    "command": "bin/pulsar standalone"
    "deploy":
      "resources":
        "limits":
          "cpus": "1.0"
          "memory": "1.2G"
        "reservations":
          "cpus": "0.5"
          "memory": "1.2G"
    "environment":
      "PULSAR_MEM": "-Xms700M -Xmx700M"
    "image": "docker.io/apachepulsar/pulsar:3.3.1"
    "ports":
    - "6650:6650"
    - "8080:8080"
    "restart": "on-failure:100"
    "volumes":
    - "pulsar-conf:/pulsar/conf"
    - "pulsar-data:/pulsar/data"
  ```

If you see that the Pulsar container (looking at the containers with `docker ps`) is immediately stuck in a restart loop, increasing the memory allocations for the `init-pulsar` container may help.

**Comment by jonabert** [comment]
> Hey @jonabert do you find it works if you leave it for a bit longer? Which docker compose are you using?

Openai cassandra on Linux Ubuntu 22.04 , will try to leave it running a bit longer. I had to remap grafana ports in the compose file, but quite sure it's not related

**Comment by jonabert** [comment]
Will also increase the resources for pulsar and give you feedback

**Comment by JackColquitt** [comment]
@jonabert to be totally safe, as I noted in the [Get Started Guide](https://trustgraph.ai/docs/getstarted#running-trustgraph), wait around `120 seconds` after launching TrustGraph before running the loader script while Pulsar and Cassandra fully stabilize into a working state.

**Comment by cybermaggedon** [comment]
Just a suggestion, once you have launched, try logging into Grafana (localhost:3000 or whatever port you mapped it to.  User admin, password admin by default.

Look at the request rate / pub-sub backlog visuals.  If you have a good long list of subscribers on Pulsar the system is started.

![image](https://github.com/user-attachments/assets/4aabfd38-3531-48ab-b734-7a506c2fe886)

Also check `podman ps -a` to see if anything failed.  The pulsar-init process is just a setup process, so that is expected to exit, but everything else is expected to stay running.

**Comment by JackColquitt** [comment]
Hi @jonabert, the good news is, I think I see the problem.

![tg_error](https://github.com/user-attachments/assets/c2c3a956-c2c0-4d95-8a1e-6ab203fc3285)

I made a `caution` note in the [Get Started Guide](https://trustgraph.ai/docs/getstarted#trustgraph-as-docker-compose-files). 

> All tokens, paths, and authentication files must be set PRIOR to launching a Docker Compose file.

You need to set your OpenAI key, **before**, launching TrustGraph. If you see those warnings, fully shut down TrustGraph with:

```
docker compose -f tg-launch-openai-cassandra.yaml down -v
```

Then set your key:
```
export OPENAI_KEY=<your_key>
```

Then, relaunch TrustGraph:
```
docker compose -f tg-launch-openai-cassandra.yaml up -d

```

**Comment by jonabert** [comment]
Hi Jack, my OPENAI_KEY was always set, the dockers just couldn't read them for some reason as you can see below, that's the real issue (the key is working, I checked it independently) 
![image](https://github.com/user-attachments/assets/2af0d502-2029-4210-9c97-bdb0e1724fda)

**Comment by cybermaggedon** [comment]
That error message is from docker-compose, not one of the containers, so there's something stopping the variable making its way to docker-compose.

OPENAI_KEY is set, is it definitely exported?  This would show you if it has been promoted to environment variable...
```
env | grep OPENAI_KEY
```
If it's not there, you need to export it `export OPENAI_KEY`

**Comment by jonabert** [comment]
![image](https://github.com/user-attachments/assets/57e4f5cd-fdb3-4af1-8439-7e0460fce32a)
as you see it's being set and correctly identified as environment variable by the OS

**Comment by cybermaggedon** [comment]
Oh wait, I see.  You're using `sudo` which resets the environment. Give this a try...?
```
sudo env OPENAI_KEY=${OPENAI_KEY} docker-compose -f whatever.yaml up -d
```

**Comment by jonabert** [comment]
fantastic, that works! Thank you so much!

**Comment by cybermaggedon** [comment]
Awesome, thanks for sharing the issue, and reporting back.
