### ISSUE TITLE
Exception:  cannot access local variable 's' where it is not associated with a value

### ISSUE THREAD

**Issue by jonabert** [trustgraph-ai/trustgraph#49]
the knowledge graph process in the happy flow (NASA pdf ingestion) gives a string of exceptions
output of the command sudo docker logs trustgraph-kg-extract-definitions-1
![image](https://github.com/user-attachments/assets/1b75c12f-cbe0-4992-8124-9703f74fd2ad)

**Comment by JackColquitt** [comment]
On it's face, that seems like the LLM is not returning correctly formed responses. Which model are you using in OpenAI? Also, what are you seeing if you run:

```
docker logs trustgraph-text-completion-1
```

**Comment by cybermaggedon** [comment]
Think it's fixed here...
https://github.com/trustgraph-ai/trustgraph/pull/50
Just running tests

**Comment by cybermaggedon** [comment]
Refactoring broke code initialisation , fixed in 0.8.3, appreciate your report, thanks!
