### ISSUE TITLE
ModuleNotFoundError: No module named 'trustgraph'

### ISSUE THREAD

**Issue by cam-s-hunt** [trustgraph-ai/trustgraph#64]
- Running `tg-launch-ollama-cassandra.yml`. 
- Attempt to ingets a variety of PDF files: `scripts/load-pdf sources/*.pdf`
- Receive this error:
`Traceback (most recent call last):
  File "/home/rig/docker/trustgraph/scripts/load-pdf", line 9, in <module>
    from trustgraph.schema import Document, Source, document_ingest_queue
ModuleNotFoundError: No module named 'trustgraph'`

**Comment by cam-s-hunt** [comment]
Resolved with restarting the session and...

`export PYTHONPATH=.`

and then

`. env/bin/activate`

It would be amazing if the scripts were a part of one of the containers so we wouldn't have to do anything on the host machine, just call something like `docker exec -it <container> load-pdf <host dir mapped to internal container path>`

**Comment by JackColquitt** [comment]
This is mostly being handled by new `trustgraph-cli` approach.
